<?php

namespace ContainerAtp3tLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiant2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cXGvmlo.App\Entity\Etudiant' shared service.
     *
     * @return \App\Entity\Etudiant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cXGvmlo": it references class "App\\Entity\\Etudiant" but no such service exists.');
    }
}
