<?php

namespace ContainerHuDRd5t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_84fFt1XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.84fFt1X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.84fFt1X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chambre' => ['privates', '.errored..service_locator.84fFt1X.App\\Entity\\Chambre', NULL, 'Cannot autowire service ".service_locator.84fFt1X": it references class "App\\Entity\\Chambre" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chambre' => 'App\\Entity\\Chambre',
            'em' => '?',
        ]);
    }
}
