<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRDK6Mbd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRDK6Mbd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRDK6Mbd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRDK6Mbd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRDK6Mbd\App_KernelDevDebugContainer([
    'container.build_hash' => 'RDK6Mbd',
    'container.build_id' => '6fe11366',
    'container.build_time' => 1594262865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRDK6Mbd');
