<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYXDY8LJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYXDY8LJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYXDY8LJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYXDY8LJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYXDY8LJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'YXDY8LJ',
    'container.build_id' => '04b68e59',
    'container.build_time' => 1594134583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYXDY8LJ');
