<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtp3tLi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtp3tLi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtp3tLi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtp3tLi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtp3tLi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Atp3tLi',
    'container.build_id' => 'e4533923',
    'container.build_time' => 1594399040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtp3tLi');
